apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgres-coach-host: postgres-coach-service
  postgres-coach-database: coach_db
  postgres-swimmer-host: postgres-swimmer-service
  postgres-swimmer-database: swimmer_db
  postgres-port: "5432"
