spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
    ssl:
      enabled: ${RABBIT_SSL_ENABLED:false}
    queue:
      delete-coach-queue: delete.coach.queue
      get-coach-swimmers-queue: get.coach.swimmers.queue
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-5997569.okta.com/oauth2/default

server:
  port: ${SERVER_PORT}
