services:

  coach:
    build:
      context: ../coach
      dockerfile: Dockerfile
    container_name: coach
    depends_on:
      - postgres-coach-db
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: postgres-coach-db
      POSTGRES_DATABASE: coach_db
      POSTGRES_PORT: 5432
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
    networks:
      - net

  postgres-coach-db:
    image: postgres
    container_name: postgres-coach-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - net

  swimmer:
    build:
      context: ../swimmer
      dockerfile: Dockerfile
    container_name: swimmer
    depends_on:
      - postgres-swimmer-db
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: postgres-swimmer-db
      POSTGRES_DATABASE: swimmer_db
      POSTGRES_PORT: 5432
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
    networks:
      - net

  postgres-swimmer-db:
    image: postgres
    container_name: postgres-swimmer-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - net

  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    container_name: gateway
    depends_on:
      - coach
      - swimmer
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
    networks:
      - net

  frontend:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - gateway
    ports:
      - "8083:80"
    networks:
      - net

  rabbitmq:
    image: rabbitmq:4.2.0-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - net

networks:
  net:
