services:

  coach:
    build:
      context: ../coach
      dockerfile: Dockerfile
    container_name: coach
    restart: always
    depends_on:
      - postgres-coach-db
    ports:
      - "8081:8081"
    networks:
      - net

  postgres-coach-db:
    image: postgres
    container_name: postgres-coach-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coach_db
    networks:
      - net

  swimmer:
    build:
      context: ../swimmer
      dockerfile: Dockerfile
    container_name: swimmer
    restart: always
    depends_on:
      - coach
      - postgres-swimmer-db
    ports:
      - "8082:8082"
    networks:
      - net

  postgres-swimmer-db:
    image: postgres
    container_name: postgres-swimmer-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: swimmer_db
    networks:
      - net

  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: always
    depends_on:
      - coach
      - swimmer
    ports:
      - "8080:8080"
    networks:
      - net

  frontend:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - coach
      - swimmer
      - gateway
    ports:
      - "8083:80"
    networks:
      - net

networks:
  net:
