spring:
  datasource:
    url: jdbc:postgresql://postgres-coach-db:5432/coach_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-7447834.okta.com/oauth2/default

server:
  port: 8081

lab3:
  swimmer:
    url: http://swimmer:8082
